[package]
cairo-version = "=2.12.1"
name = "utp_dojo"
version = "0.1.0"

[lib]

[scripts]
migrate = "sozo build && sozo migrate"                      # scarb run migrate

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.3" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.3" }
starknet = ">=2.12.1"

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]
#allowed-libfuncs-list.name = "experimental"

[dev-dependencies]
cairo_test = "=2.12.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.3" }

[features]
default = []